taka3/taka3/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using taka3.Models;
using taka3.Services;
using Microsoft.AspNet.Identity;

namespace taka3.Controllers
{
    public class FriendController : Controller
    {
        private ApplicationDbContext m_db = new ApplicationDbContext();

        FollowingService fservice = new FollowingService();

        public ActionResult Index()
        {
            return View(fservice.GetAllFriendList().ToList());
        }

        [HttpPost]
        public ActionResult FollowUser(string userID)
        {
            string currUserId = User.Identity.GetUserId();
            var fService = new FollowingService();
            fService.AddFollowingToUser(currUserId, userID);

			//Redirectar á prófílinn og sendir id notandans með	-Védís
			return RedirectToAction("FriendProfilePage", "Home", new { userId = userID });
        }

        // GET: friends/Details/5
        public ActionResult Details(int? id)
        {
            FriendModel friendModel = m_db.FriendModel.Find(id);
            if (friendModel == null)
            {
                return HttpNotFound();
            }
            return View(friendModel);
        }

        [Authorize]
        public ActionResult GetUserFriends()
        {
            var userid = User.Identity.GetUserId();

            var model = fservice.GetUserFriendInfoById(userid);

            return View(model);
        }

    }
}

taka3/taka3/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using taka3.Models;
using taka3.Services;
using Microsoft.AspNet.Identity;

namespace taka3.Controllers
{
    
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private readonly GroupService _groups;

        private GroupService gService = new GroupService();

        public GroupsController()
        {
            _groups = new GroupService();
        }

        // GET: Groupst
        public ActionResult Index()
        {
            return View(_groups.AllGroups().ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        [Authorize]
        public ActionResult GetUserGroups()
        {
            var userid = User.Identity.GetUserId();

            var model = gService.GetGroupsForUser(userid);

            return View(model);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,GroupName,UserName")] GroupModel groupModel)
        {
            if (ModelState.IsValid)
            {
                groupModel.UserName = User.Identity.GetUserName();
                _groups.AddGroup(groupModel);
                return RedirectToAction("Index");
            }

            return View(groupModel);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,GroupName,UserName")] GroupModel groupModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(groupModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groupModel);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GroupModel groupModel = db.Group.Find(id);
            db.Group.Remove(groupModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult AddGroupMember(FormCollection collection)
        {
            
            GroupUser newGroupUser = new GroupUser();
            newGroupUser.GroupId = Convert.ToInt32(collection["GroupId"]);
            newGroupUser.UserId = collection["UserId"];
            gService.AddGroupUser(newGroupUser);

            return RedirectToAction("Details", new { id = newGroupUser.GroupId});  
        }

        [HttpGet]
        public ActionResult AddGroupMember(string id)
        {
            AddFriendToGroupModelView model = new AddFriendToGroupModelView();

            var followingService = new FollowingService(); //búa til tilvik
            var userid = User.Identity.GetUserId();

            ViewBag.GroupID = id;
            
          
           var friendlist = followingService.MyFollowingList(userid);
           model.GetAllFriends = friendlist;
            
            //return View(friendlist);
            return View(model);
        }
    }
}

taka3/taka3/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using taka3.Models;
using taka3.Services;
using Microsoft.AspNet.Identity;

namespace taka3.Controllers
{
	//Controller sem tekur á móti póstum frá notendum (myndum/statusum)	-Védís
    public class PostController : Controller
    {
		UserPostService userService = new UserPostService();

	   //steindor gerði fall sem sækir myndir
	   public ActionResult FileUpload(HttpPostedFileBase file, int? postid, string postBody)
	   {
		   string postbody = postBody;
		   string photo = null; //Bætti við svo hægt að seiva mynd í gagnagrunn	-Védís
		   string photonameshort = null;

		   if (file != null)
		   {
			   string pic = System.IO.Path.GetFileName(file.FileName);
			   string path = System.IO.Path.Combine(Server.MapPath("~/Content/images"), pic);
			   // file is uploaded
			   file.SaveAs(path);
			   photo = path;
			   photonameshort = pic;
		   }

		   UserPost model = new UserPost();
		   model.UserID = User.Identity.GetUserId();
		   model.Image = photo;
		   model.ImageName = photonameshort;
		   model.PostBody = postbody;
		   model.DateAndTime = DateTime.Now;

		   userService.AddPosts(model);

		   //Redirectar aftur á newsfeedið
           return RedirectToAction("NewsFeed", "Home");
	   }
	}
}

taka3/taka3/Views/Shared/_AddCommentPartial.cshtml
@using (Html.BeginForm("CommentUpload", "Comment", FormMethod.Post, new { enctype = "application/x-www-form-urlencoded"}))
{
    <input type="hidden" name="commentid" value="" />
    <input type="hidden" name="postid" id="postid" value="postid" />
    <label for="comment">Tjáning um málefnið</label>
    <input type="text" name="commentBody" id="commentBody" />
    <input type="submit" value="PostComment" class="submit" />
}

taka3/taka3/Views/Shared/_AddPostGroup.cshtml
@using (Html.BeginForm("FileUpload", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" name="postid" value="" />
    <label for="file">Setja inn mynd og/eða stöðuuppfærslu:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />
    <!--Textabox sem tekur við Status-->
    <input type="text" name="postBody" id="postBody" />
    <input type="submit" value="Post" class="submit" />
}

taka3/taka3/Views/Shared/_AddPostPartial.cshtml
@using (Html.BeginForm("FileUpload", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" name="postid" value="" />
    <label for="file">Setja inn mynd og/eða stöðuuppfærslu:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />
    <!--Textabox sem tekur við Status-->
    <input type="text" name="postBody" id="postBody" />
    <input type="submit" value="Post" class="submit" />
}

taka3/taka3/Views/Shared/_FollowButton.cshtml
@model taka3.Models.ProfilePageViewModel

@using (Html.BeginForm("FollowUser", "Friend", FormMethod.Post, new { userId = "userId" }))
{
    @Html.Hidden("userID", Model.userID)
    <button type="submit" id="status" class="button" value="True"><span>follow</span></button>
}

taka3/taka3/Views/Shared/_Layout.cshtml
<!--Bætti við ActionLink tökkum í bannerinn og linkaði þá við Views. 
    Lét vísa í _LogoutPartial svo það væri hægt að láta login birtast annarsstaðar en logout.
    Stillti Sidebar svo innihald hans sjáist bara þegar notandi er loggaður inn.   -Védís-->

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
    @if (Request.IsAuthenticated)
    {
        //Fanney lagað möppur
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Fréttaveita","NewsFeed","Home")</li>
            <li>@Html.ActionLink("Hópar", "Index", "Groups")</li>
            <li>@Html.ActionLink("Heimasvæði","ProfilePage","Home" )</li>


            <!---Fanney að brasa með hamborgara
            <a id="nav-toggle" href="#"><span></span></a>
            <div id="burger" style="display:none">
            </div> -->
        </ul>
      
                    @Html.Partial("_LogoutPartial")
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HÓPUR 36</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

taka3/taka3/Views/Shared/_LogoutPartial.cshtml
<!--Við vildum ekki hafa Login í bannernum svo ég bjó til þetta partial view sem er bara með Logout
    svo að það væri hægt að birta login á öðrum stað.   -Védís-->
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    }
}

taka3/taka3/Views/Shared/_SearchPartialView.cshtml
<!--fanney, leita að notanda

<search name =" searchList" id="searchList" style="border: solid 1px #cccccc; vertical-align: middle">
    <option value="Default_Contact">Contact</option>
</search>
<input type="text" style="border: solid 1px #cccccc; vertical-align: middle" value="Search.." id="txtSearch" name="txtSearch"/>

<img src="/Images/i_search.gif" style="vertical-align: middle; height:16px;" alt="" onclick="searchClick()"/>

$('#SearchResult').html(responseText); -->

taka3/taka3/Views/Shared/_ToDoPartial.cshtml
<div class="pull-left">
    <p>Verkefnin mín</p>
    <ul>
        <li>Stebbi</li>
        <li>Stóð</li>
        <li>Á</li>
        <li>Ströndu</li>
    </ul>
</div>